In [1]:
# python 3.10.2 
import sys
import os
import numpy as np          # 1.22.0
import pandas as pd         # 1.3.4

In [2]:
print(sys.version)
print('{}: {}'.format(np.__name__, np.__version__))
print(pd.__version__)

3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
numpy: 1.23.0
1.3.4

In [3]:
sys.path.append(os.path.abspath('../'))
from IPython.display import display

In [4]:
from evaluation import Evaluator
from data import FncData

FNC_DATA_PATH = '../../fnc-1/'

### Tablica službenih rješenja

In [5]:
competition_data = FncData(
    bodies_csv_path=os.path.join(FNC_DATA_PATH, 'competition_test_bodies.csv'),
    stances_csv_path=os.path.join(FNC_DATA_PATH, 'competition_test_stances.csv'))
competition_data.headlines_bodies_and_stances.head()

,Headline,Body ID,Stance,articleBody
0,Ferguson riots: Pregnant woman loses eye after...,2008,unrelated,A RESPECTED senior French police officer inves...
1,Apple Stores to install safes to secure gold A...,2008,unrelated,A RESPECTED senior French police officer inves...
2,Pregnant woman loses eye after police shoot be...,2008,unrelated,A RESPECTED senior French police officer inves...
3,We just found out the #Ferguson Protester who ...,2008,unrelated,A RESPECTED senior French police officer inves...
4,Police Chief In Charge of Paris Attacks Commit...,2008,discuss,A RESPECTED senior French police officer inves...

### Tablice rješenja BERT modela

In [6]:
bert_entailment_with_athene_data = FncData(
    bodies_csv_path=os.path.join(FNC_DATA_PATH, 'competition_test_bodies.csv'),
    stances_csv_path=os.path.join('combined_bert_entailment', \
        'comp_autosave_after_epoch_10_athene.csv'))
bert_entailment_with_athene_data.headlines_bodies_and_stances.head()

,Headline,Body ID,Stance,articleBody
0,Ferguson riots: Pregnant woman loses eye after...,2008,unrelated,A RESPECTED senior French police officer inves...
1,Apple Stores to install safes to secure gold A...,2008,unrelated,A RESPECTED senior French police officer inves...
2,Pregnant woman loses eye after police shoot be...,2008,unrelated,A RESPECTED senior French police officer inves...
3,We just found out the #Ferguson Protester who ...,2008,unrelated,A RESPECTED senior French police officer inves...
4,Police Chief In Charge of Paris Attacks Commit...,2008,agree,A RESPECTED senior French police officer inves...

In [7]:
bert_entailment_with_talos_data = FncData(
    bodies_csv_path=os.path.join(FNC_DATA_PATH, 'competition_test_bodies.csv'),
    stances_csv_path=os.path.join('combined_bert_entailment', \
        'comp_autosave_after_epoch_10_talos.csv'))
bert_entailment_with_talos_data.headlines_bodies_and_stances.head()

,Headline,Body ID,Stance,articleBody
0,Ferguson riots: Pregnant woman loses eye after...,2008,unrelated,A RESPECTED senior French police officer inves...
1,Apple Stores to install safes to secure gold A...,2008,unrelated,A RESPECTED senior French police officer inves...
2,Pregnant woman loses eye after police shoot be...,2008,unrelated,A RESPECTED senior French police officer inves...
3,We just found out the #Ferguson Protester who ...,2008,unrelated,A RESPECTED senior French police officer inves...
4,Police Chief In Charge of Paris Attacks Commit...,2008,agree,A RESPECTED senior French police officer inves...

In [8]:
bert_entailment_with_ucl_data = FncData(
    bodies_csv_path=os.path.join(FNC_DATA_PATH, 'competition_test_bodies.csv'),
    stances_csv_path=os.path.join('combined_bert_entailment', \
        'comp_autosave_after_epoch_10_ucl.csv'))
bert_entailment_with_ucl_data.headlines_bodies_and_stances.head()

,Headline,Body ID,Stance,articleBody
0,Ferguson riots: Pregnant woman loses eye after...,2008,unrelated,A RESPECTED senior French police officer inves...
1,Apple Stores to install safes to secure gold A...,2008,unrelated,A RESPECTED senior French police officer inves...
2,Pregnant woman loses eye after police shoot be...,2008,unrelated,A RESPECTED senior French police officer inves...
3,We just found out the #Ferguson Protester who ...,2008,unrelated,A RESPECTED senior French police officer inves...
4,Police Chief In Charge of Paris Attacks Commit...,2008,agree,A RESPECTED senior French police officer inves...

In [9]:
competition_stances = competition_data.headlines_and_stances['Stance']
evaluator = Evaluator()

### Rezultati zajedničkog BERT modela i modela tima Athene

In [10]:
bert_entailment_with_athene_stances = \
    bert_entailment_with_athene_data.headlines_and_stances['Stance']
evaluator.show(competition_stances, bert_entailment_with_athene_stances)
print('Unrelated dodan naknadno:')
print('\tAgree\tDisagree\tDiscuss\n\t{}\t{}\t\t{}'.format(36, 2, 100))

              Agree  Disagree  Discuss  Unrelated  Accuracy (%)
0      Agree    955       195      596        157         50.18
1   Disagree    115       210      223        149         30.13
2    Discuss    379       204     3531        350         79.10
3  Unrelated     19         4      115      18211         99.25
4    Overall      0         0        0          0         90.14

Results:
    score: 9676.75
    score percentage: 83.0533
Unrelated dodan naknadno:
	Agree	Disagree	Discuss
	36	2		100

In [11]:
score_matrix = evaluator.getScoreMatrix(competition_stances, bert_entailment_with_athene_stances)
score_matrix['Agree'].iloc[3] = 36
score_matrix['Disagree'].iloc[3] = 2
score_matrix['Discuss'].iloc[3] = 100
score_matrix

              Agree  Disagree  Discuss  Unrelated  Accuracy (%)
0      Agree    955       195      596        157         50.18
1   Disagree    115       210      223        149         30.13
2    Discuss    379       204     3531        350         79.10
3  Unrelated     36         2      100      18211         99.25
4    Overall      0         0        0          0         90.14

### Rezultati zajedničkog BERT modela i modela tima Talos

In [12]:
bert_entailment_with_talos_stances = \
    bert_entailment_with_talos_data.headlines_and_stances['Stance']
evaluator.show(competition_stances, bert_entailment_with_talos_stances)
print('Unrelated dodan naknadno:')
print('\tAgree\tDisagree\tDiscuss\n\t{}\t{}\t\t{}'.format(41, 0, 197))

              Agree  Disagree  Discuss  Unrelated  Accuracy (%)
0      Agree    928       199      592        184         48.77
1   Disagree    114       229      239        115         32.86
2    Discuss    386       224     3620        234         81.09
3  Unrelated     35         0      203      18111         98.70
4    Overall      0         0        0          0         90.06

Results:
    score: 9743.25
    score percentage: 83.6241
Unrelated dodan naknadno:
	Agree	Disagree	Discuss
	41	0		197

In [13]:
score_matrix = evaluator.getScoreMatrix(competition_stances, bert_entailment_with_talos_stances)
score_matrix['Agree'].iloc[3] = 41
score_matrix['Disagree'].iloc[3] = 0
score_matrix['Discuss'].iloc[3] = 197
score_matrix

              Agree  Disagree  Discuss  Unrelated  Accuracy (%)
0      Agree    928       199      592        184         48.77
1   Disagree    114       229      239        115         32.86
2    Discuss    386       224     3620        234         81.09
3  Unrelated     41         0      197      18111         98.70
4    Overall      0         0        0          0         90.06

### Rezultati zajedničkog BERT modela i modela tima UCL

In [14]:
bert_entailment_with_ucl_stances = \
    bert_entailment_with_ucl_data.headlines_and_stances['Stance']
evaluator.show(competition_stances, bert_entailment_with_ucl_stances)
print('Unrelated dodan naknadno:')
print('\tAgree\tDisagree\tDiscuss\n\t{}\t{}\t\t{}'.format(124, 13, 249))

              Agree  Disagree  Discuss  Unrelated  Accuracy (%)
0      Agree    976       201      612        114         51.29
1   Disagree    114       224      243        116         32.14
2    Discuss    382       237     3583        262         80.26
3  Unrelated     53         3      330      17963         97.90
4    Overall      0         0        0          0         89.51

Results:
    score: 9721.0
    score percentage: 83.4331
Unrelated dodan naknadno:
	Agree	Disagree	Discuss
	124	13		249

In [15]:
score_matrix = evaluator.getScoreMatrix(competition_stances, bert_entailment_with_ucl_stances)
score_matrix['Agree'].iloc[3] = 124
score_matrix['Disagree'].iloc[3] = 13
score_matrix['Discuss'].iloc[3] = 249
score_matrix

              Agree  Disagree  Discuss  Unrelated  Accuracy (%)
0      Agree    976       201      612        114         51.29
1   Disagree    114       224      243        116         32.14
2    Discuss    382       237     3583        262         80.26
3  Unrelated    124        13      249      17963         97.90
4    Overall      0         0        0          0         89.51

In [16]:
# def getWrongUnrelated(bert_entailment_with_team_data, competition_stances):
#     bert_entailment_with_team_all_data = pd.concat([
#         bert_entailment_with_team_data.headlines_and_stances, \
#             pd.DataFrame(dict(ActualStance=competition_stances))], axis=1)
#     bert_entailment_with_team_all_data['i'] = \
#         bert_entailment_with_team_all_data.index
#     bert_entailment_with_team_unrelated = bert_entailment_with_team_all_data[
#         (bert_entailment_with_team_all_data['ActualStance'] == 'unrelated') \
#         & (bert_entailment_with_team_all_data['Stance'] != 'unrelated')]
#     return bert_entailment_with_team_unrelated

In [17]:
# bert_entailment_with_talos_unrelated = getWrongUnrelated(
#     bert_entailment_with_talos_data, competition_stances
# )
# bert_entailment_with_talos_unrelated.to_csv(
#     'bert_entailment_with_talos_unrelated.csv')

# bert_entailment_with_athene_unrelated = getWrongUnrelated(
#     bert_entailment_with_athene_data, competition_stances
# )
# bert_entailment_with_athene_unrelated.to_csv(
#     'bert_entailment_with_athene_unrelated.csv')

# bert_entailment_with_ucl_unrelated = getWrongUnrelated(
#     bert_entailment_with_ucl_data, competition_stances
# )
# bert_entailment_with_ucl_unrelated.to_csv(
#     'bert_entailment_with_ucl_unrelated.csv')